### ISSUE TITLE
Icons are not Loading

### ISSUE THREAD

**Issue by Sandeep-source** [DSDmark/Shoes-webTemplate#5]
Social Icon are not loading
![image](https://user-images.githubusercontent.com/61611561/210150855-384d3a7b-5ee0-4efd-bf94-c3fb2240f11c.png)
![image](https://user-images.githubusercontent.com/61611561/210150861-523eb724-e64f-4c85-8715-a4b78f3dbf1d.png)

**Comment by DSDmark** [comment]
Hi @Sandeep-source,

Thank you for submitting this issue and bringing it to my attention. I apologize for any inconvenience you may have experienced.

I will take a look at this issue as soon as possible and do my best to resolve it. If you have any additional information or resources that might be helpful, please let us know.

In the meantime, if you have any questions or concerns or if you thinks you have an idea that, make significant change to improve the code or documentation. Then, you can fork that repository and make a change and submit your Pull Request. And please, if you need, don't hesitate to reach out.
